[features]
seeds = false
skip-lint = false
[programs.localnet]
tic_tac_toe = "CohEjtwR97zmoii1mBhpxxbhdMdNunoBTFSd7SpY2mgr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/shaquillehobbsdaley/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
